set(_CATKIN_CURRENT_PACKAGE "neck")
set(neck_VERSION "0.0.0")
set(neck_MAINTAINER "bbb <bbb@todo.todo>")
set(neck_PACKAGE_FORMAT "1")
set(neck_BUILD_DEPENDS "roscpp" "std_msgs")
set(neck_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(neck_BUILDTOOL_DEPENDS "catkin")
set(neck_BUILDTOOL_EXPORT_DEPENDS )
set(neck_EXEC_DEPENDS "roscpp" "std_msgs")
set(neck_RUN_DEPENDS "roscpp" "std_msgs")
set(neck_TEST_DEPENDS )
set(neck_DOC_DEPENDS )
set(neck_DEPRECATED "")