set(_CATKIN_CURRENT_PACKAGE "xingzhe")
set(xingzhe_VERSION "0.0.0")
set(xingzhe_MAINTAINER "bbb <bbb@todo.todo>")
set(xingzhe_PACKAGE_FORMAT "1")
set(xingzhe_BUILD_DEPENDS "roscpp" "std_msgs")
set(xingzhe_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(xingzhe_BUILDTOOL_DEPENDS "catkin")
set(xingzhe_BUILDTOOL_EXPORT_DEPENDS )
set(xingzhe_EXEC_DEPENDS "roscpp" "std_msgs")
set(xingzhe_RUN_DEPENDS "roscpp" "std_msgs")
set(xingzhe_TEST_DEPENDS )
set(xingzhe_DOC_DEPENDS )
set(xingzhe_DEPRECATED "")