set(_CATKIN_CURRENT_PACKAGE "prupwm")
set(prupwm_VERSION "0.0.0")
set(prupwm_MAINTAINER "bbb <2676902@todo.todo>")
set(prupwm_PACKAGE_FORMAT "1")
set(prupwm_BUILD_DEPENDS "roscpp" "std_msgs" "message_generation")
set(prupwm_BUILD_EXPORT_DEPENDS "message_runtime" "roscpp" "std_msgs")
set(prupwm_BUILDTOOL_DEPENDS "catkin")
set(prupwm_BUILDTOOL_EXPORT_DEPENDS )
set(prupwm_EXEC_DEPENDS "message_runtime" "roscpp" "std_msgs")
set(prupwm_RUN_DEPENDS "message_runtime" "roscpp" "std_msgs")
set(prupwm_TEST_DEPENDS )
set(prupwm_DOC_DEPENDS )
set(prupwm_DEPRECATED "")