set(_CATKIN_CURRENT_PACKAGE "body")
set(body_VERSION "0.0.0")
set(body_MAINTAINER "bbb <2676902@todo.todo>")
set(body_PACKAGE_FORMAT "1")
set(body_BUILD_DEPENDS "roscpp" "std_msgs" "message_generation")
set(body_BUILD_EXPORT_DEPENDS "message_runtime" "roscpp" "std_msgs")
set(body_BUILDTOOL_DEPENDS "catkin")
set(body_BUILDTOOL_EXPORT_DEPENDS )
set(body_EXEC_DEPENDS "message_runtime" "roscpp" "std_msgs")
set(body_RUN_DEPENDS "message_runtime" "roscpp" "std_msgs")
set(body_TEST_DEPENDS )
set(body_DOC_DEPENDS )
set(body_DEPRECATED "")