set(_CATKIN_CURRENT_PACKAGE "eye")
set(eye_VERSION "0.0.0")
set(eye_MAINTAINER "bbb <bbb@todo.todo>")
set(eye_PACKAGE_FORMAT "1")
set(eye_BUILD_DEPENDS "libopencv-dev" "image_transport" "roscpp" "cv_bridge" "sensor_msgs" "nodelet" "camera_info_manager")
set(eye_BUILD_EXPORT_DEPENDS "libopencv-dev" "image_transport" "roscpp" "cv_bridge" "sensor_msgs" "nodelet" "camera_info_manager")
set(eye_BUILDTOOL_DEPENDS "catkin")
set(eye_BUILDTOOL_EXPORT_DEPENDS )
set(eye_EXEC_DEPENDS "libopencv-dev" "image_transport" "roscpp" "cv_bridge" "sensor_msgs" "nodelet" "camera_info_manager")
set(eye_RUN_DEPENDS "libopencv-dev" "image_transport" "roscpp" "cv_bridge" "sensor_msgs" "nodelet" "camera_info_manager")
set(eye_TEST_DEPENDS )
set(eye_DOC_DEPENDS )
set(eye_DEPRECATED "")