set(_CATKIN_CURRENT_PACKAGE "arm")
set(arm_VERSION "0.0.0")
set(arm_MAINTAINER "bbb <2676902@qq.com>")
set(arm_PACKAGE_FORMAT "1")
set(arm_BUILD_DEPENDS "roscpp" "std_msgs")
set(arm_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(arm_BUILDTOOL_DEPENDS "catkin")
set(arm_BUILDTOOL_EXPORT_DEPENDS )
set(arm_EXEC_DEPENDS "roscpp" "std_msgs")
set(arm_RUN_DEPENDS "roscpp" "std_msgs")
set(arm_TEST_DEPENDS )
set(arm_DOC_DEPENDS )
set(arm_DEPRECATED "")