set(_CATKIN_CURRENT_PACKAGE "monkey")
set(monkey_VERSION "0.0.0")
set(monkey_MAINTAINER "bbb <bbb@todo.todo>")
set(monkey_PACKAGE_FORMAT "1")
set(monkey_BUILD_DEPENDS "roscpp" "std_msgs")
set(monkey_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(monkey_BUILDTOOL_DEPENDS "catkin")
set(monkey_BUILDTOOL_EXPORT_DEPENDS )
set(monkey_EXEC_DEPENDS "roscpp" "std_msgs")
set(monkey_RUN_DEPENDS "roscpp" "std_msgs")
set(monkey_TEST_DEPENDS )
set(monkey_DOC_DEPENDS )
set(monkey_DEPRECATED "")